In [1]:
%matplotlib notebook
import pandas as pd, numpy as np
import matplotlib.pyplot as plt
import sys

sys.path.append('../')
pd.options.display.max_columns = 35

data_path = '../data/raw/'

In [2]:
train = pd.read_csv(data_path + "train_1.csv", header=0, delimiter=";",decimal=',',
                    parse_dates=['date'], index_col='date')

In [3]:
train.head(5)

insee  tH2_obs  capeinsSOL0  ciwcH20   clwcH20 ddH10_rose4  \
date                                                                        
2014-01-01   6088001      5.5     0.198757      0.0  0.000000         4.0   
2014-01-01  31069001      4.8     8.590036      0.0  0.000000         3.0   
2014-01-01  33281001      8.9    69.203856      0.0  0.000001         3.0   
2014-01-01  35281001      6.8    65.270316      0.0  0.000000         3.0   
2014-01-01  59343001      5.4     5.932505      0.0  0.000000         3.0   

               ffH10      flir1SOL0    fllat1SOL0     flsen1SOL0  \
date                                                               
2014-01-01  1.970260 -386960.595711 -94260.682523  -40545.510054   
2014-01-01  2.755962 -200181.123871   2282.951687   14399.918192   
2014-01-01  3.411283  -62310.340297   9483.691316   64790.365136   
2014-01-01  4.655633  -61612.120075 -48356.475831  127450.659115   
2014-01-01  5.855930  -39553.109955  -1022.914242  117800.171480   

              flvis1SOL0  hcoulimSOL0       huH2  iwcSOL0  nbSOL0_HMoy  \
date                                                                     
2014-01-01  3.600000e-12    66.600368  79.211738      0.0     0.000000   
2014-01-01  3.600000e-12    57.954614  83.862960      0.0     0.012709   
2014-01-01  3.600000e-12   202.985582  95.711708      0.0     4.792424   
2014-01-01  3.600000e-12   343.974193  90.178385      0.0     7.074669   
2014-01-01  3.600000e-12   656.972741  92.680476      0.0     7.995791   

               nH20  ntSOL0_HMoy        pMER0   rr1SOL0     rrH20       tH2  \
date                                                                          
2014-01-01  0.00000     4.173220  1019.543734  0.000000  0.000000  9.034338   
2014-01-01  0.00000     5.736559  1018.290035  0.000000  0.000000  3.853128   
2014-01-01  0.15494     7.844538  1016.139756  0.081315  0.005008  8.585184   
2014-01-01  0.00000     7.377704  1009.321502  0.029946  0.008139  7.304130   
2014-01-01  0.00000     7.995791  1008.724301  0.000000  0.000000  5.829715   

            tH2_VGrad_2.100  tH2_XGrad  tH2_YGrad  tpwHPA850    ux1H10  \
date                                                                     
2014-01-01        -0.084999   0.007725  -0.013024   3.852825  1.330320   
2014-01-01         1.396138   0.005036   0.000810   8.476699 -2.040020   
2014-01-01         0.387329   0.001372   0.000010   7.643070  3.029610   
2014-01-01        -0.089267   0.000401  -0.000067   7.089030 -1.027446   
2014-01-01        -0.489606   0.000204  -0.000191   4.546075  2.802554   

             vapcSOL0    vx1H10  ech     mois  
date                                           
2014-01-01  10.664653 -2.853134    1  janvier  
2014-01-01  15.462043  3.019614    1  janvier  
2014-01-01  17.343600  4.889849    1  janvier  
2014-01-01  13.981847  8.079973    1  janvier  
2014-01-01   9.941609  7.955489    1  janvier

In [4]:
train.tail(1)

insee  tH2_obs  capeinsSOL0  ciwcH20  clwcH20 ddH10_rose4  \
date                                                                       
2016-05-30  75114001     15.1     37.96799      0.0      0.0         1.0   

               ffH10     flir1SOL0     fllat1SOL0    flsen1SOL0    flvis1SOL0  \
date                                                                            
2016-05-30  4.787774 -36131.218648 -104907.174372 -29352.106044  3.600000e-12   

            hcoulimSOL0       huH2  iwcSOL0  nbSOL0_HMoy  nH20  ntSOL0_HMoy  \
date                                                                          
2016-05-30   634.417512  84.116919      0.0     6.808911   0.0          8.0   

                  pMER0   rr1SOL0  rrH20        tH2  tH2_VGrad_2.100  \
date                                                                   
2016-05-30  1008.687416  0.000033    0.0  15.530561        -1.158119   

            tH2_XGrad  tH2_YGrad  tpwHPA850    ux1H10  vapcSOL0    vx1H10  \
date                                                                        
2016-05-30   0.000501   0.001025  13.568253  4.275935  29.26325 -8.666735   

            ech mois  
date                  
2016-05-30    1  mai

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6167 entries, 2014-01-01 to 2016-05-30
Data columns (total 30 columns):
insee              6167 non-null int64
tH2_obs            6167 non-null float64
capeinsSOL0        5586 non-null float64
ciwcH20            6160 non-null float64
clwcH20            6048 non-null float64
ddH10_rose4        6041 non-null object
ffH10              6041 non-null float64
flir1SOL0          6160 non-null float64
fllat1SOL0         6167 non-null float64
flsen1SOL0         6160 non-null float64
flvis1SOL0         6160 non-null float64
hcoulimSOL0        6160 non-null float64
huH2               6041 non-null float64
iwcSOL0            6160 non-null float64
nbSOL0_HMoy        6160 non-null float64
nH20               5845 non-null float64
ntSOL0_HMoy        6160 non-null float64
pMER0              6027 non-null float64
rr1SOL0            6160 non-null float64
rrH20              6041 non-null float64
tH2                6041 non-null float64
tH2_VGrad_2.100  

ddH10_rose4, mois object type => category ?  
There are missing values

In [6]:
train.describe(include='all')

insee      tH2_obs  capeinsSOL0       ciwcH20      clwcH20  \
count   6.167000e+03  6167.000000  5586.000000  6.160000e+03  6048.000000   
unique           NaN          NaN          NaN           NaN          NaN   
top              NaN          NaN          NaN           NaN          NaN   
freq             NaN          NaN          NaN           NaN          NaN   
mean    4.390000e+07    10.714788    37.366002  6.747272e-08     0.000005   
std     2.246953e+07     5.624477   104.122266  1.289975e-06     0.000034   
min     6.088001e+06    -6.100000     0.000000  0.000000e+00     0.000000   
25%     3.106900e+07     6.700000     0.000000  0.000000e+00     0.000000   
50%     3.528100e+07    10.500000     1.029342  0.000000e+00     0.000000   
75%     6.712400e+07    14.500000    20.048593  0.000000e+00     0.000000   
max     7.511400e+07    29.799999  1083.809402  4.305547e-05     0.000413   

       ddH10_rose4        ffH10      flir1SOL0    fllat1SOL0     flsen1SOL0  \
count         6041  6041.000000    6160.000000  6.167000e+03    6160.000000   
unique           4          NaN            NaN           NaN            NaN   
top            4.0          NaN            NaN           NaN            NaN   
freq          2044          NaN            NaN           NaN            NaN   
mean           NaN     3.021334 -187621.781077 -3.007864e+04   40626.427357   
std            NaN     1.910197   93786.779163  7.978076e+04   73618.358613   
min            NaN     0.008230 -503863.736917 -1.453469e+06 -224336.423922   
25%            NaN     1.736467 -254116.866438 -3.643746e+04   -2320.273261   
50%            NaN     2.591331 -206017.425408 -5.467513e+02   21096.272421   
75%            NaN     3.807748 -116794.746585  6.696667e+03   70471.989502   
max            NaN    15.310204   78624.299681  9.387913e+04  641199.521351   

          flvis1SOL0  hcoulimSOL0         huH2      iwcSOL0  nbSOL0_HMoy  \
count   6.160000e+03  6160.000000  6041.000000  6160.000000  6160.000000   
unique           NaN          NaN          NaN          NaN          NaN   
top              NaN          NaN          NaN          NaN          NaN   
freq             NaN          NaN          NaN          NaN          NaN   
mean    3.600000e-12   304.393988    82.958615     0.019749     2.194061   
std     8.078591e-28   375.040197    11.797864     0.336138     2.905182   
min     3.600000e-12     0.466309    15.270923     0.000000     0.000000   
25%     3.600000e-12    46.977809    76.730183     0.000000     0.000000   
50%     3.600000e-12   159.982197    85.493204     0.000000     0.351207   
75%     3.600000e-12   419.951200    91.789160     0.000000     4.247805   
max     3.600000e-12  3617.658173    99.997908    10.107500     8.000000   

               nH20  ntSOL0_HMoy        pMER0      rr1SOL0        rrH20  \
count   5845.000000  6160.000000  6027.000000  6160.000000  6041.000000   
unique          NaN          NaN          NaN          NaN          NaN   
top             NaN          NaN          NaN          NaN          NaN   
freq            NaN          NaN          NaN          NaN          NaN   
mean       0.263000     4.723653  1016.782426     0.082548     0.003303   
std        1.261355     3.317032     8.563395     0.486920     0.021460   
min        0.000000     0.000000   982.386670     0.000000     0.000000   
25%        0.000000     0.760056  1011.759314     0.000000     0.000000   
50%        0.000000     6.022196  1017.029292     0.000000     0.000000   
75%        0.000000     7.995756  1022.196427     0.000000     0.000000   
max        8.331533     8.000000  1043.259009    14.344218     0.727914   

                tH2  tH2_VGrad_2.100    tH2_XGrad    tH2_YGrad    tpwHPA850  \
count   6041.000000      6041.000000  6041.000000  6041.000000  6160.000000   
unique          NaN              NaN          NaN          NaN          NaN   
top             NaN              NaN          NaN          NaN          NaN   
freq       

**tH2_obs** :	Observation de la température à 2 mètres in situ- au point station (prédictant)  
**capeinsSOL0**: 	Energie potentielle convective  
**ciwcH20**: 	Fraction de glace nuageuse à 20 mètres  
**clwcH20**: 	Fraction d'eau nuageuse à 20 mètres  
**ddH10_rose4**: 	Direction du vent à 10 mètres en rose4  
**ffH10**: 	Force du vent à 10 mètres en m/s  
**flir1SOL0**: 	Flux Infra-rouge en J/m2  
**fllat1SOL0**: 	Flux de chaleur latente en J/m2  
**flsen1SOL0**: 	Flux de chaleur sensible en J/m2  
**flvis1SOL0**: 	Flux visible en J/m2  
**hcoulimSOL0**: 	Hauteur de la couche limite en mètres  
**huH2**: 	Humidité 2mètres en %  
**iwcSOL0**: 	Réservoir neige kg/m2 (équivalent en eau liquide des chutes de neige)  
**nbSOL0_HMoy**: 	Nébulosité basse (moyenne sur les 6 points de grille autour de la station) (fraction en octat du ciel occulté)  
**nH20**: 	Fraction nuageuse à 20 mètres  
**ntSOL0_HMoy**: 	Nébulosité totale (moyenne sur les 6 points de grille autour de la station)  
**pMER0**: 	Pression au niveau de la mer  
**rr1SOL0**: 	Précipitation horaire au niveau du sol  
**rrH20**: 	Précipitation horaire à 20 mètres  
**tH2**: 	Température à 2 mètres du modèle AROME  
**tH2_VGrad_2.100**: 	Gradient vertical de température entre 2 mètres et 100 mètres  
**tH2_XGrad**: 	Gradient zonal de température à 2 mètres  
**tH2_YGrad**: 	Gradient méridien de température à 2 mètres  
**tpwHPA850**: 	Température potentielle au niveau 850 hPa  
**ux1H10**: 	Rafale 1 minute du vent à 10 mètres composante zonale  
**vapcSOL0**: 	Colonne de vapeur d'eau  
**vx1H10**: 	Rafale 1 minute du vent à 10 mètres composante verticale  
**ech** : 	Echéance de validité = date   

# Rows with nan

In [7]:
# Total missings values by variable
pd.DataFrame(train.isnull().sum()).T

insee  tH2_obs  capeinsSOL0  ciwcH20  clwcH20  ddH10_rose4  ffH10  \
0      0        0          581        7      119          126    126   

   flir1SOL0  fllat1SOL0  flsen1SOL0  flvis1SOL0  hcoulimSOL0  huH2  iwcSOL0  \
0          7           0           7           7            7   126        7   

   nbSOL0_HMoy  nH20  ntSOL0_HMoy  pMER0  rr1SOL0  rrH20  tH2  \
0            7   322            7    140        7    126  126   

   tH2_VGrad_2.100  tH2_XGrad  tH2_YGrad  tpwHPA850  ux1H10  vapcSOL0  vx1H10  \
0              126        126        126          7     126         7     119   

   ech  mois  
0    0     0

In [8]:
for i in np.where(train.isnull().sum() == 126)[0]:
    print(np.where(np.asanyarray(pd.isnull(train.iloc[:,i]))))

(array([2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663,
       2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674,
       2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685,
       2686, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 2695, 2696,
       2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707,
       2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718,
       2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729,
       2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740,
       2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751,
       2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762,
       2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 4627, 4628,
       4629, 4630, 4631, 4632, 4633]),)
(array([2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663,
       2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674,
       26

Same row location for missing vals for these variables

In [9]:
# Rows with missing val
np.where(train.isnull().sum(axis=1).values > 0)[0]

array([ 539,  540,  541,  542,  543,  544,  545,  546,  547,  548,  549,
        550,  551,  552,  553,  554,  555,  556,  557,  558,  559,  560,
        561,  562,  563,  564,  565,  566,  567,  568,  569,  570,  571,
        572,  573,  574,  575,  576,  577,  578,  579,  580,  581,  582,
        583,  584,  585,  586,  587,  588,  589,  590,  591,  592,  593,
        594,  595,  596,  597,  598,  599,  600,  601,  602,  603,  604,
        605,  606,  607,  608,  609,  610,  611,  612,  613,  614,  615,
        616,  617,  618,  619,  620,  621,  622,  623,  624,  625,  626,
        627,  628,  629,  819,  820,  821,  822,  823,  824,  825,  826,
        827,  828,  829,  830,  831,  832,  833,  834,  835,  836,  837,
        838,  839, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548,
       1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559,
       1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570,
       1571, 1572, 1573, 1574, 1575, 1576, 1577, 15

In [10]:
# Coordinate of missing values
np.where(np.asanyarray(pd.isnull(train)))

(array([ 539,  540,  541, ..., 4633, 4633, 4633]),
 array([ 2,  2,  2, ..., 25, 26, 27]))

Lets have a look to 1 row

In [49]:
pd.DataFrame(train.iloc[2653-7*3,:]).T

insee tH2_obs capeinsSOL0 ciwcH20 clwcH20 ddH10_rose4    ffH10  \
2015-01-12  6088001     8.6   0.0640884       0       0         4.0  3.52355   

           flir1SOL0 fllat1SOL0 flsen1SOL0 flvis1SOL0 hcoulimSOL0     huH2  \
2015-01-12   -369955    -120083   -19096.3    3.6e-12     367.236  69.2346   

           iwcSOL0 nbSOL0_HMoy nH20 ntSOL0_HMoy    pMER0 rr1SOL0 rrH20  \
2015-01-12       0           0    0           0  1027.16       0     0   

                tH2 tH2_VGrad_2.100   tH2_XGrad   tH2_YGrad tpwHPA850  \
2015-01-12  12.7426       0.0238568  0.00212395 -0.00562426   7.18519   

             ux1H10 vapcSOL0  vx1H10 ech     mois  
2015-01-12  3.71358  9.45647 -3.8209   1  janvier

## Missing values by file

In [3]:
df_miss_val = pd.DataFrame(columns=train.columns).drop(['insee', 'tH2_obs', 'ech', 'mois'], axis=1)

for i in range(1,37):
    tmp =pd.read_csv(data_path + 'train_' + str(i) + '.csv', 
                     header=0, delimiter=";",decimal=',',
                     parse_dates=['date'], index_col='date').drop(['insee', 'tH2_obs', 'ech', 'mois'], axis=1)
    missing_val_r, missing_val_c = np.where(np.asanyarray(pd.isnull(tmp)))
    tmp_row_df = [[] for _ in range(len(tmp.columns.values))]
    for row, col in zip(missing_val_r, missing_val_c):
        tmp_row_df[col].append(row)
    tmp_row_df = np.array(tmp_row_df).reshape([1,-1])
    # total number of missing val per col
#     df_miss_val = pd.concat([df_miss_val, pd.DataFrame(tmp.isnull().sum()).T], axis=0)
    df_miss_val = pd.concat([df_miss_val, pd.DataFrame(tmp_row_df, columns=tmp.columns)], axis=0, ignore_index=True)
df_miss_val

capeinsSOL0  \
0   [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
1   [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
2   [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
3   [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
4   [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
5   [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
6   [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
7   [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
8   [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
9   [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
10  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
11  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
12  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
13  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
14  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
15  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
16  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
17  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
18  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
19  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
20  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
21  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
22  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
23  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
24  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
25  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
26  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
27  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
28  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
29  [539, 540, 541, 542, 543, 544, 545, 546, 547, ...   
30  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...   
31  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...   
32  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...   
33  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...   
34  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...   
35  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...   

                                              ciwcH20  \
0          [4627, 4628, 4629, 4630, 4631, 4632, 4633]   
1          [4200, 4201, 4202, 4203, 4204, 4205, 4206]   
2          [4200, 4201, 4202, 4203, 4204, 4205, 4206]   
3          [4200, 4201, 4202, 4203, 4204, 4205, 4206]   
4          [4200, 4201, 4202, 4203, 4204, 4205, 4206]   
5                                                  []   
6          [4200, 4201, 4202, 4203, 4204, 4205, 4206]   
7          [4200, 4201, 4202, 4203, 4204, 4205, 4206]   
8                                                  []   
9          [4200, 4201, 4202, 4203, 4204, 4205, 4206]   
10                                                 []   
11         [4200, 4201, 4202, 4203, 4204, 4205, 4206]   
12                                                 []   
13                                                 []   
14         [4200, 4201, 4202, 4203, 4204, 4205, 4206]   
15                                                 []   
16                                                 []   
17                                                 []   
18         [4200, 4201, 4202, 4203, 4204, 4205, 4206]   
19                                                 []   
20                                                 []   
21         [4627, 4628, 4629, 4630, 4631, 4632, 4633]   
22         [4627, 4628, 4629, 4630, 4631, 4632, 4633]   
23         [4627, 4628, 4629, 4630, 4631, 4632, 4633]   
24         [4627, 4628, 4629, 4630, 4631, 4632, 4633]   
25         [4627, 4628, 4629, 4630, 4631, 4632, 4633]   
26         [4627, 4628, 4629, 4630, 4631, 4632, 4633]   
27         [4627, 4628, 4629, 4630, 4631, 4632, 4633]   
28         [4627, 4628, 4629, 4630, 4631, 4632, 4633]   
29                                                 []   
30  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...   
31  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...   
32  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,.

In [4]:
np.corrcoef(map(len, df_miss_val.loc[0])), df_miss_val.loc[0]

(1.0, capeinsSOL0        [539, 540, 541, 542, 543, 544, 545, 546, 547, ...
 ciwcH20                   [4627, 4628, 4629, 4630, 4631, 4632, 4633]
 clwcH20            [2653, 2654, 2655, 2656, 2657, 2658, 2659, 266...
 ddH10_rose4        [2653, 2654, 2655, 2656, 2657, 2658, 2659, 266...
 ffH10              [2653, 2654, 2655, 2656, 2657, 2658, 2659, 266...
 flir1SOL0                 [4627, 4628, 4629, 4630, 4631, 4632, 4633]
 fllat1SOL0                                                        []
 flsen1SOL0                [4627, 4628, 4629, 4630, 4631, 4632, 4633]
 flvis1SOL0                [4627, 4628, 4629, 4630, 4631, 4632, 4633]
 hcoulimSOL0               [4627, 4628, 4629, 4630, 4631, 4632, 4633]
 huH2               [2653, 2654, 2655, 2656, 2657, 2658, 2659, 266...
 iwcSOL0                   [4627, 4628, 4629, 4630, 4631, 4632, 4633]
 nbSOL0_HMoy               [4627, 4628, 4629, 4630, 4631, 4632, 4633]
 nH20               [2653, 2654, 2655, 2656, 2657, 2658, 2659, 266...
 ntSOL0_HMoy   

In [5]:
## For sum sur chaque vector: good method or not to see correlation
for i in df_miss_val.columns.values:
    print(sum(df_miss_val.loc[0,i]), '--', i)

1197441 -- capeinsSOL0
32410 -- ciwcH20
322728 -- clwcH20
355138 -- ddH10_rose4
355138 -- ffH10
32410 -- flir1SOL0
0 -- fllat1SOL0
32410 -- flsen1SOL0
32410 -- flvis1SOL0
32410 -- hcoulimSOL0
355138 -- huH2
32410 -- iwcSOL0
32410 -- nbSOL0_HMoy
1035258 -- nH20
32410 -- ntSOL0_HMoy
396781 -- pMER0
32410 -- rr1SOL0
355138 -- rrH20
355138 -- tH2
355138 -- tH2_VGrad_2.100
355138 -- tH2_XGrad
355138 -- tH2_YGrad
32410 -- tpwHPA850
355138 -- ux1H10
32410 -- vapcSOL0
336546 -- vx1H10


Pb : dont allow to keep the coordinate

In [25]:
dict_corr_matrix_of_cols_with_matching_missing_vals = dict()
for file_number in range(len(df_miss_val)): #replace .loc[0] with .loc[file_number]
    dict_corr_matrix_of_cols_with_matching_missing_vals[file_number+1] = dict()
    len_missing_val_per_cols = map(len, df_miss_val.loc[file_number])
#     print('Data missing for the variables:', np.array(len_vect_cols))
    
    for len_vect in set(len_missing_val_per_cols):
        dict_corr_matrix_of_cols_with_matching_missing_vals[file_number+1][len_vect] = dict()
        if len_vect > 0:
#             print('Variables of missing values:', len_vect)
            cols_matching_len_vect = np.where(np.array(len_missing_val_per_cols) == len_vect)[0]
            if len(cols_matching_len_vect) > 1:
                dict_corr_matrix_of_cols_with_matching_missing_vals[file_number+1][len_vect]['matching_cols'] = cols_matching_len_vect
                corr = np.corrcoef(list(df_miss_val.iloc[file_number,cols_matching_len_vect]))
                dict_corr_matrix_of_cols_with_matching_missing_vals[file_number+1][len_vect]['corr_mat'] = corr

In [24]:
dict_corr_matrix_of_cols_with_matching_missing_vals

{1: {0: {},
  7: {'corr_mat': array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
          [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]]),
   'matching_cols': array([ 1,  5,  7,  8,  9, 11, 12, 14, 16, 22, 24])},
  119: {'corr_mat': array([[ 1.       ,  0.4700074],
          [ 0.4700074,  1.       ]]), 'matching_cols': array([ 2, 25])},
  126: {'corr_mat': array([[ 1.,  

vectors of similar length have the same coordinates

Dealing with missing val :  
https://gallery.cortanaintelligence.com/Experiment/Methods-for-handling-missing-values-1